#!/usr/bin/env bash

parent_path=$(
    cd "$(dirname "${BASH_SOURCE[0]}")" || exit
    pwd -P
)
postgre_data_path="$parent_path/../.pgdata"
echo "PostgreSQL data path: $postgre_data_path"

if [ "$1" = "stop" ]; then
    docker stop migration-postgre >/dev/null 2>&1
elif [ "$1" = "rm" ]; then
    docker stop migration-postgre >/dev/null 2>&1
    docker rm migration-postgre >/dev/null 2>&1
else
    status=$(docker ps -a -f name=migration-postgre --format "{{.Status}}" | cut -d' ' -f1)
    case $status in
    "Exited") docker start migration-postgre >/dev/null 2>&1 ;;
    "") docker run -d \
        --name migration-postgre \
        -p 5432:5432 \
        -e POSTGRES_USER=migrationadmin \
        -e POSTGRES_PASSWORD="password" \
        -e POSTGRES_DB="migrationdb" \
        -e PGDATA=/var/lib/postgresql/data/pgdata \
        -v "$postgre_data_path":/var/lib/postgresql/data \
        postgres ;;
    esac
fi
