storageRoot = "/tmp/migration"

[dbConfig]
host = "localhost"
port = 5432
dbName = "migrationdb"
user = "migrationadmin"
password = "password"

[inspireConfig.ipsConfig]
host = "localhost"
port = 30354