package com.quadient.wfdxml.internal.layoutnodes.email;

import com.quadient.wfdxml.api.layoutnodes.email.TMText;
import com.quadient.wfdxml.internal.NodeImpl;
import com.quadient.wfdxml.internal.xml.export.XmlExporter;

public class TMTextImpl extends NodeImpl<TMText> implements TMText {

    @Override
    public String getXmlElementName() {
        return "TMText";
    }

    @Override
    public void export(XmlExporter exporter) {
        exporter.addElementWithStringData("Type", "Simple");
        exporter.beginElement("TextContent");
        exporter.addRawXml(TEXT_CONTENT);
        exporter.endElement();
        exporter.beginElement("EscapeFlags");
        exporter.addRawXml(ESCAPE_FLAGS);
        exporter.endElement();
    }

    private static final String TEXT_CONTENT =
        "<P>&lt;!doctype html&gt;</P>"
        + "<P>&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot;</P>"
        + "<P xml:space=\"preserve\">&#x20; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;</P>"
        + "<P>&lt;head&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;title&gt;&lt;/title&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;!--[if !mso]&gt;--&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;!--&lt;![endif]--&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;/&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;style type=&quot;text/css&quot;&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20;   @@@CX:CSS@@@#outlook a {</P>"
        + "<P xml:space=\"preserve\">&#x20;     padding: 0;</P>"
        + "<P xml:space=\"preserve\">&#x20;   }</P>"
        + "<P xml:space=\"preserve\">&#x20;   body {</P>"
        + "<P xml:space=\"preserve\">&#x20;     margin: 0;</P>"
        + "<P xml:space=\"preserve\">&#x20;     padding: 0;</P>"
        + "<P xml:space=\"preserve\">&#x20;     -webkit-text-size-adjust: 100%;</P>"
        + "<P xml:space=\"preserve\">&#x20;     -ms-text-size-adjust: 100%;</P>"
        + "<P xml:space=\"preserve\">&#x20;   }</P>"
        + "<P xml:space=\"preserve\">&#x20;   table,</P>"
        + "<P xml:space=\"preserve\">&#x20;   td {</P>"
        + "<P xml:space=\"preserve\">&#x20;     border-collapse: collapse;</P>"
        + "<P xml:space=\"preserve\">&#x20;     mso-table-lspace: 0pt;</P>"
        + "<P xml:space=\"preserve\">&#x20;     mso-table-rspace: 0pt;</P>"
        + "<P xml:space=\"preserve\">&#x20;   }</P>"
        + "<P xml:space=\"preserve\">&#x20;   img {</P>"
        + "<P xml:space=\"preserve\">&#x20;     border: 0;</P>"
        + "<P xml:space=\"preserve\">&#x20;     height: auto;</P>"
        + "<P xml:space=\"preserve\">&#x20;     line-height: 100%;</P>"
        + "<P xml:space=\"preserve\">&#x20;     outline: none;</P>"
        + "<P xml:space=\"preserve\">&#x20;     text-decoration: none;</P>"
        + "<P xml:space=\"preserve\">&#x20;     -ms-interpolation-mode: bicubic;</P>"
        + "<P xml:space=\"preserve\">&#x20;   }</P>"
        + "<P xml:space=\"preserve\">&#x20;   p {</P>"
        + "<P xml:space=\"preserve\">&#x20;     display: block;</P>"
        + "<P xml:space=\"preserve\">&#x20;     margin: 13px 0;</P>"
        + "<P xml:space=\"preserve\">&#x20;   }</P>"
        + "<P xml:space=\"preserve\">&#x20;&#x20;</P>"
        + "<P>&lt;/style&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;!--[if mso]&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20;   &lt;xml&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20;   &lt;o:OfficeDocumentSettings&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20;     &lt;o:AllowPNG/&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20;     &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20;   &lt;/o:OfficeDocumentSettings&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20;   &lt;/xml&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;![endif]--&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;!--[if lte mso 11]&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20;   &lt;style type=&quot;text/css&quot;&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20;     .mj-outlook-group-fix { width:100% !important; }</P>"
        + "<P xml:space=\"preserve\">&#x20;   &lt;/style&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;![endif]--&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;style type=&quot;text/css&quot;&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20;   @media only screen and (min-width:480px) {</P>"
        + "<P xml:space=\"preserve\">&#x20;     .mj-column-per-25 {</P>"
        + "<P xml:space=\"preserve\">&#x20;       width: 25% !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;       max-width: 25%;</P>"
        + "<P xml:space=\"preserve\">&#x20;     }</P>"
        + "<P xml:space=\"preserve\">&#x20;     .mj-column-per-33-5 {</P>"
        + "<P xml:space=\"preserve\">&#x20;       width: 33.5% !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;       max-width: 33.5%;</P>"
        + "<P xml:space=\"preserve\">&#x20;     }</P>"
        + "<P xml:space=\"preserve\">&#x20;     .mj-column-per-33-33333333333333 {</P>"
        + "<P xml:space=\"preserve\">&#x20;       width: 33.33333333333333% !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;       max-width: 33.33333333333333%;</P>"
        + "<P xml:space=\"preserve\">&#x20;     }</P>"
        + "<P xml:space=\"preserve\">&#x20;     .mj-column-per-50 {</P>"
        + "<P xml:space=\"preserve\">&#x20;       width: 50% !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;       max-width: 50%;</P>"
        + "<P xml:space=\"preserve\">&#x20;     }</P>"
        + "<P xml:space=\"preserve\">&#x20;     .mj-column-per-66-5 {</P>"
        + "<P xml:space=\"preserve\">&#x20;       width: 66.5% !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;       max-width: 66.5%;</P>"
        + "<P xml:space=\"preserve\">&#x20;     }</P>"
        + "<P xml:space=\"preserve\">&#x20;     .mj-column-per-75 {</P>"
        + "<P xml:space=\"preserve\">&#x20;       width: 75% !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;       max-width: 75%;</P>"
        + "<P xml:space=\"preserve\">&#x20;     }</P>"
        + "<P xml:space=\"preserve\">&#x20;     .mj-column-per-100 {</P>"
        + "<P xml:space=\"preserve\">&#x20;       width: 100% !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;       max-width: 100%;</P>"
        + "<P xml:space=\"preserve\">&#x20;     }</P>"
        + "<P xml:space=\"preserve\">&#x20;   }</P>"
        + "<P xml:space=\"preserve\">&#x20;&#x20;</P>"
        + "<P>&lt;/style&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;style type=&quot;text/css&quot;&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20;   [owa] .mj-column-per-25 {</P>"
        + "<P xml:space=\"preserve\">&#x20;     width: 25% !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;     max-width: 25%;</P>"
        + "<P xml:space=\"preserve\">&#x20;   }</P>"
        + "<P xml:space=\"preserve\">&#x20;   [owa] .mj-column-per-33-5 {</P>"
        + "<P xml:space=\"preserve\">&#x20;     width: 33.5% !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;     max-width: 33.5%;</P>"
        + "<P xml:space=\"preserve\">&#x20;   }</P>"
        + "<P xml:space=\"preserve\">&#x20;   [owa] .mj-column-per-33-33333333333333 {</P>"
        + "<P xml:space=\"preserve\">&#x20;     width: 33.33333333333333% !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;     max-width: 33.33333333333333%;</P>"
        + "<P xml:space=\"preserve\">&#x20;   }</P>"
        + "<P xml:space=\"preserve\">&#x20;   [owa] .mj-column-per-50 {</P>"
        + "<P xml:space=\"preserve\">&#x20;     width: 50% !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;     max-width: 50%;</P>"
        + "<P xml:space=\"preserve\">&#x20;   }</P>"
        + "<P xml:space=\"preserve\">&#x20;   [owa] .mj-column-per-66-5 {</P>"
        + "<P xml:space=\"preserve\">&#x20;     width: 66.5% !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;     max-width: 66.5%;</P>"
        + "<P xml:space=\"preserve\">&#x20;   }</P>"
        + "<P xml:space=\"preserve\">&#x20;   [owa] .mj-column-per-75 {</P>"
        + "<P xml:space=\"preserve\">&#x20;     width: 75% !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;     max-width: 75%;</P>"
        + "<P xml:space=\"preserve\">&#x20;   }</P>"
        + "<P xml:space=\"preserve\">&#x20;   [owa] .mj-column-per-100 {</P>"
        + "<P xml:space=\"preserve\">&#x20;     width: 100% !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;     max-width: 100%;</P>"
        + "<P xml:space=\"preserve\">&#x20;   }</P>"
        + "<P xml:space=\"preserve\">&#x20;&#x20;</P>"
        + "<P>&lt;/style&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;style type=&quot;text/css&quot;&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20;   @media only screen and (max-width:480px) {</P>"
        + "<P xml:space=\"preserve\">&#x20;     table.mj-full-width-mobile {</P>"
        + "<P xml:space=\"preserve\">&#x20;       width: 100% !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;     }</P>"
        + "<P xml:space=\"preserve\">&#x20;     td.mj-full-width-mobile {</P>"
        + "<P xml:space=\"preserve\">&#x20;       width: auto !important;</P>"
        + "<P xml:space=\"preserve\">&#x20;     }</P>"
        + "<P xml:space=\"preserve\">&#x20;   }</P>"
        + "<P xml:space=\"preserve\">&#x20;&#x20;</P>"
        + "<P>&lt;/style&gt;</P>"
        + "<P>&lt;/head&gt;</P>"
        + "<P>&lt;body style=&quot;background-color:@@@CX:BACKGROUND@@@;&quot;&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20;&#x20;<O Id=\"Def.EmailsHeader\"/></P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;div&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20;  &#x20;<O Id=\"Def.EmailsBody\"/></P>"
        + "<P xml:space=\"preserve\">&#x20; &lt;/div&gt;</P>"
        + "<P xml:space=\"preserve\">&#x20;&#x20;<O Id=\"Def.EmailsFooter\"/></P>"
        + "<P>&lt;/body&gt;</P>"
        + "<P>&lt;/html&gt;</P>";

    private static final String ESCAPE_FLAGS =
        "<EscapeFlag Index=\"0\" Flag=\"0\"/>"
        + "<EscapeFlag Index=\"159\" Flag=\"1\"/>"
        + "<EscapeFlag Index=\"161\" Flag=\"0\"/>"
        + "<EscapeFlag Index=\"177\" Flag=\"1\"/>"
        + "<EscapeFlag Index=\"179\" Flag=\"0\"/>"
        + "<EscapeFlag Index=\"197\" Flag=\"1\"/>"
        + "<EscapeFlag Index=\"199\" Flag=\"0\"/>"
        + "<EscapeFlag Index=\"253\" Flag=\"1\"/>"
        + "<EscapeFlag Index=\"255\" Flag=\"0\"/>"
        + "<EscapeFlag Index=\"272\" Flag=\"1\"/>"
        + "<EscapeFlag Index=\"274\" Flag=\"0\"/>"
        + "<EscapeFlag Index=\"343\" Flag=\"1\"/>"
        + "<EscapeFlag Index=\"345\" Flag=\"0\"/>"
        + "<EscapeFlag Index=\"414\" Flag=\"1\"/>"
        + "<EscapeFlag Index=\"416\" Flag=\"0\"/>"
        + "<EscapeFlag Index=\"971\" Flag=\"1\"/>"
        + "<EscapeFlag Index=\"973\" Flag=\"0\"/>"
        + "<EscapeFlag Index=\"1150\" Flag=\"1\"/>"
        + "<EscapeFlag Index=\"1152\" Flag=\"0\"/>"
        + "<EscapeFlag Index=\"1284\" Flag=\"1\"/>"
        + "<EscapeFlag Index=\"1286\" Flag=\"0\"/>"
        + "<EscapeFlag Index=\"2058\" Flag=\"1\"/>"
        + "<EscapeFlag Index=\"2060\" Flag=\"0\"/>"
        + "<EscapeFlag Index=\"2765\" Flag=\"1\"/>"
        + "<EscapeFlag Index=\"2767\" Flag=\"0\"/>"
        + "<EscapeFlag Index=\"3064\" Flag=\"1\"/>"
        + "<EscapeFlag Index=\"3070\" Flag=\"0\"/>"
        + "<EscapeFlag Index=\"3076\" Flag=\"1\"/>"
        + "<EscapeFlag Index=\"3084\" Flag=\"0\"/>"
        + "<EscapeFlag Index=\"3091\" Flag=\"1\"/>"
        + "<EscapeFlag Index=\"3095\" Flag=\"0\"/>";
}
