name: Dependency check

on:
  pull_request:
  workflow_dispatch:

jobs:
  dependencies:
    timeout-minutes: 30

    name: Dependency check ${{ matrix.project }}
    runs-on: ubuntu-latest

    env:
      VERSION: latest
      API_KEY: ${{ secrets.G_API_KEY }}
      NVD_PW: ${{ secrets.G_NVD_PW }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dependency check migration-library
        working-directory: ./migration-library
        run: |
          ./gradlew dependencyCheckAnalyze --info

          curl -X POST --insecure -F "upload=@./build/reports/dependency-check-report.xml" \
            "https://osquality-api.quadient.group/scan/api/report/?apiKey=$API_KEY&stream=migration-library&versionName=$VERSION"

      - name: Dependency check migration-examples
        working-directory: ./migration-examples
        run: |
          ./gradlew dependencyCheckAnalyze --info

          curl -X POST --insecure -F "upload=@./build/reports/dependency-check-report.xml" \
            "https://osquality-api.quadient.group/scan/api/report/?apiKey=$API_KEY&stream=migration-examples&versionName=$VERSION"

      - name: Dependency check wfd-xml
        working-directory: ./wfd-xml
        run: |
          ./gradlew dependencyCheckAggregate --info

          curl -X POST --insecure -F "upload=@./build/reports/dependency-check-report.xml" \
            "https://osquality-api.quadient.group/scan/api/report/?apiKey=$API_KEY&stream=wfd-xml&versionName=$VERSION"
