name: Dependency check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  dependencies:
    timeout-minutes: 30

    name: Dependency check
    runs-on: ubuntu-latest

    env:
      VERSION: latest
      API_KEY: ${{ secrets.G_API_KEY }}
      NVD_PW: ${{ secrets.G_NVD_PW }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dependency check
        run: |
          log() {
            printf "$(date --rfc-3339=ns) \e[0;34mINFO\033[0m %s\n" "$1"
          }

          log "Running dependency check for migration-library"
          (cd migration-library && ./gradlew dependencyCheckAnalyze)
          log "Uploading report for migration-library"
          curl -X POST --insecure -F "upload=@./migration-library/build/reports/dependency-check-report.xml" \
            "https://osquality-api.quadient.group/scan/api/report/?apiKey=$API_KEY&stream=migration-library&versionName=$VERSION"

          log "Running dependency check for migration-examples"
          (cd migration-examples && ./gradlew dependencyCheckAnalyze)
          log "Uploading report for migration-examples"
          curl -X POST --insecure -F "upload=@./migration-examples/build/reports/dependency-check-report.xml" \
            "https://osquality-api.quadient.group/scan/api/report/?apiKey=$API_KEY&stream=migration-examples&versionName=$VERSION"

          log "Running dependency check for wfd-xml"
          (cd wfd-xml && ./gradlew dependencyCheckAggregate)
          log "Uploading report for wfd-xml"
          curl -X POST --insecure -F "upload=@./wfd-xml/build/reports/dependency-check-report.xml" \
            "https://osquality-api.quadient.group/scan/api/report/?apiKey=$API_KEY&stream=wfd-xml&versionName=$VERSION"

          log "Running dependency check for migration-app"
          (cd migration-app && ./gradlew dependencyCheckAnalyze)
          log "Uploading report for migration-app"
          curl -X POST --insecure -F "upload=@./migration-app/build/reports/dependency-check-report.xml" \
            "https://osquality-api.quadient.group/scan/api/report/?apiKey=$API_KEY&stream=migration-app&versionName=$VERSION"

