name: Nightly build

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  nightly:
    timeout-minutes: 30
    permissions:
      contents: write

    name: Build nightly
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew :migration-app:buildDistZip

      - name: Get version
        run: |
          version=$(./gradlew -q :migration-app:printVersion)
          echo "MIG_VERSION=$version" >> "$GITHUB_ENV"

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: migration-app-${{ env.MIG_VERSION }}.zip
          path: migration-app/build/dist/migration-app-*.zip

