name: Nightly build

on:
  schedule:
    - cron: '0 2 * * *'
  push:
    tags:
    - 'tip'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  nightly:
    timeout-minutes: 30
    permissions:
      contents: write

    name: Build nightly
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Tag ref
        run: |
          git config user.name "github-actions"
          git tag -fa tip -m "Continuous Release" ${GITHUB_SHA}
          git push --force origin tip

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew :migration-app:buildDistZip

      - name: Get version
        run: |
          version=$(./gradlew -q :migration-app:printVersion)
          echo "MIG_VERSION=$version" >> "$GITHUB_ENV"

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: migration-app-${{ env.MIG_VERSION }}
          path: migration-app/build/tmp/dist

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: true
          draft: false
          artifacts: migration-app/build/dist/*.zip
